#Variables creadas
from src.settings.dominio.variables_dominio import DOMINIO, DOMINIO_ATRIBUTOS, DOMINIO_URL, DOMINIO_BASE_DN, DOMINIO_USUARIO_PRUEBA, DOMINIO_USUARIO_PRUEBA_CONTRASENA, DOMINIO_PUERTO, DOMINIO_FILTRO_BUSQUEDA;

__all__ = [
    "DOMINIO",
    "DOMINIO_ATRIBUTOS",
    "DOMINIO_URL",
    "DOMINIO_BASE_DN",
    "DOMINIO_USUARIO_PRUEBA",
    "DOMINIO_USUARIO_PRUEBA_CONTRASENA",
    "DOMINIO_PUERTO",
    "DOMINIO_FILTRO_BUSQUEDA"
]